- Bug fixes and improvements

diff --git a/advanced b/advanced
--- a/advanced
+++ b/advanced
@@ -8,12 +8,14 @@ HISTFILE=~/.bash_history
 # Absolute paths to executables - Specify the versions we want to use. We don't want to use whatever is in ${PATH} (as specified in the assignment)
 CAT=/usr/bin/cat
 CLEAR=/usr/bin/clear
+CP=/usr/bin/cp
 GREP=/usr/bin/grep
 FIND=/usr/bin/find
 MKDIR=/usr/bin/mkdir
 PRINTF=/usr/bin/printf
 
-# Use the built in for echo
+# Use the built in for ulimit and exit
+EXIT="command exit"
 ULIMIT="command ulimit"
 
 function showcpunumber() {
@@ -46,14 +48,14 @@ function findandcopy() {
 	destination=${2}
 
 	if ! $MKDIR -p "${destination}" 2>/dev/null ; then
-    	$PRINTF "\nFailed to create ${destination}. Exiting.\n"
-		exit 1
+    		$PRINTF "\nFailed to create ${destination}. Exiting.\n"
+		$EXIT 3
 	fi
 	
 	# Find any files that match the wildcard specified. Exec a copy of the found file to the destination and redirect STDERR to /dev/null as we want to handle errors ourself.
-	if ! $FIND .  -type f -name "${wildcard}" -exec cp {} "${destination}" \; ; then
+	if ! $FIND .  -type f -name "${wildcard}" -exec $CP {} "${destination}" \; ; then
 		$PRINTF "\nFailed to copy files matching ${wildcard} to ${destination}.\n"
-		exit 1
+		$EXIT 3
 	fi
 		
 	$PRINTF "\nFiles have been copied matching ${wildcard} to ${destination}\n"
@@ -62,14 +64,14 @@ function findandcopy() {
 function showusage() {
 	$PRINTF "\nusage: $0 -p - to show the amount of cpus available in the system"
 	$PRINTF "\nusage: $0 -o - to show the maximum number of open files allowed per user"
-	$PRINTF "\nusage: $0 -b [wildcard] [destination] - searches for all files that match the wildcard specified and copies them to the destination specified."
-	$PRINTF "\nusage:"
+	$PRINTF "\nusage: $0 -b [wildcard] [destination] - searches for all files that match the wildcard specified and copies them to the destination specified.\n"
+	$EXIT 3
 }
 
 if [ -z "$1" ]; then
 	$PRINTF "\nNo arguments supplied. Usage examples are :\n"
 	showusage
-	exit 1
+	$EXIT 3
 fi
 
 ${CLEAR}
